### ISSUE TITLE
renderXML in editablegrid-mysql-example does not create xml for "data".

### ISSUE THREAD

**Issue by jerseysal** [jybeaujean/editablegrid-mysql-example#14]
When I tried to run the example, the xml produced stopped after "MetaData".  The example produced the header portion but there was no data.  The database was set up correctly.  I noticed that the EditableGrid.php packaged with the example was different than the one in the base release so I replaced the EditableGrid.php in the example with the one in the latest release and it now works.  

This is a great package and I really appreciate all the work that went into it.  Thanks...

**Comment by jybeaujean** [comment]
Thanks. I've updated EditableGrid.php in the repo.
