### ISSUE TITLE
setCellRenderer: Invalid Column: action

### ISSUE THREAD

**Issue by VFederau** [jybeaujean/editablegrid-mysql-example#15]
12.01.2014 - Hello, Please can you help me. 
An error occurs in current demo files. "setCellRenderer: Invalid Column: action"
What can i do? (I need the delete function for the gridrow)

**Comment by jybeaujean** [comment]
Check that this line is present in loaddata.php : 

$grid->addColumn('action', 'Action', 'html', NULL, false, 'id');

**Comment by VFederau** [comment]
Hello Mr Beaujean,

yes this line is present.

But - no stress - i has a workaround with inputs and this works well.

with kindly regards

V.Federau

 

Gesendet: Mittwoch, 14. Januar 2015 um 16:33 Uhr
Von: "Jean-Yves Beaujean" <notifications@github.com>
An: jybeaujean/editablegrid-mysql-example <editablegrid-mysql-example@noreply.github.com>
Cc: VFederau <victoria.federau@gmx.net>
Betreff: Re: [editablegrid-mysql-example] setCellRenderer: Invalid Column: action (#15)


Check that this line is present in loaddata.php :

$grid->addColumn('action', 'Action', 'html', NULL, false, 'id');

**Comment by jybeaujean** [comment]
I've just pushed some updates that could fix your problem.
