### ISSUE TITLE
HighCharts library not loaded!

### ISSUE THREAD

**Issue by rmingas** [jybeaujean/editablegrid-mysql-example#16]
The latest untouched download version shows the message "HighCharts library not loaded" and the "rows per page" feature is not working too

**Comment by webismymind** [comment]
This has just been fixed by commit 9238c90511469a770ab399623e665f1906285889.

**Comment by jybeaujean** [comment]
Fixed in commit : https://github.com/jybeaujean/editablegrid-mysql-example/commit/36bbd42062810014fd07f486d4bada20cf1f99ee
