### ISSUE TITLE
Name columns in loaddata from a Table

### ISSUE THREAD

**Issue by Leyff** [jybeaujean/editablegrid-mysql-example#17]
just like the name say, i like to know if there is a way to do this with a bucle for and database, like 
for (content)
{
grid->
}

**Comment by jybeaujean** [comment]
Sorry, i don't understand what you mean... 

If you want to rename a column, use : 

$grid->addColumn('firstname', 'Firstname', 'string');  

arg1 'firstname' : key in the data arrat
arg2 'Firstname' : column label
arg2 'string' : datatype/
