### ISSUE TITLE
Displayed Rows Number

### ISSUE THREAD

**Issue by rmingas** [jybeaujean/editablegrid-mysql-example#18]
Is there a function to show (on header or footer) the number of rows displayed with or without filter(s). 
Something like the image below...

![screenshot](https://cloud.githubusercontent.com/assets/10027461/6670535/67181e9c-cbff-11e4-9b68-31561745dc8a.jpg)

**Comment by jybeaujean** [comment]
Hi,
use : 
EditableGrid.prototype.getRowCount()  : Returns the number of rows
or : 
EditableGrid.prototype.getUnfilteredRowCount() : Returns the number of rows, not taking the filter into account if any

**Comment by rmingas** [comment]
Which file(s) is this function on mysql example?

**Comment by rmingas** [comment]
I'm unable to find both referred functions on MySQL version wish is the one I'm using and has no editablegrid.js file but editablegrid-2.1.0-b13.js

Any help available?
