### ISSUE TITLE
Combobox into column question

### ISSUE THREAD

**Issue by XinYiMan** [jybeaujean/editablegrid-mysql-example#19]
I would like to understand how to parameterize the query goes to populate the combobox with the name of my column Tg_Filter.

For I would that the query was

select Tg_Filter, VALUE from T_TG WHERE Tg_Filter = ????

Where Is That ???? is equivalent to the field Tg_Filter table T_Main

How can I do?

Table structure

T_MAIN

Id integer autoincrement
FullName string
Tg_Filter integer

T_TG
Id integer autoincrement
Tg_Filter integer
Value string

T_Main

1;Francesco;1
2;Andrea;2
3;Sara;2
4;Carmen;2

T_TG
1;1;stringa1
2;1;stringa2
3;2;stringa3
4;2;stringa4

My Code

// create a new EditableGrid object
$grid = new EditableGrid();
$db_tablename = (isset($_GET['db_tablename'])) ? $_GET['db_tablename'] : 'T_UTENTI';

	$connection = new PDO($str_conn,$config['db_user'],$config['db_password']);
	/* 
	*  Add columns. The first argument of addColumn is the name of the field in the databse. 
	*  The second argument is the label that will be displayed in the header
	*/

	$grid->addColumn('ID', 'MyID', 'integer', NULL, false); 	
	$grid->addColumn('FULLNAME', 'MyFullName', 'string');  
	$grid->addColumn('Tg_Filter', 'MyFilter', 'string',fetch_pairs($connection,'select Tg_Filter, VALUE from T_TG WHERE Tg_Filter=???? '),true);  
	$grid->addColumn('action', 'ACTION', 'html', NULL, false, 'ID');

	$app=$connection->prepare('SELECT * FROM T_Main');
	$app->execute();

	$result = $app->fetchAll();

	$connection = null;

// send data to the browser
$grid->renderXML($result);

**Comment by jybeaujean** [comment]
If you want to create a combobox with all possible values from T_TG, select only T_Filter from T_TG : 

$grid->addColumn('Tg_Filter', 'MyFilter', 'string',fetch_pairs($connection,'select Tg_Filter, VALUE from T_TG  '),true);
