### ISSUE TITLE
Input Mask

### ISSUE THREAD

**Issue by rmingas** [jybeaujean/editablegrid-mysql-example#21]
I've managed to add an Input mask in the add window. But when it comes to update a record row it doesn't work (I'm using jquery.inputmask.js plugin)

**Comment by rmingas** [comment]
Any suggestions or is it definitely not possible?

**Comment by jybeaujean** [comment]
I think it's possible because there is no limit to the cell editor system. 
But without code or console log or error message, I can't help you.

**Comment by rmingas** [comment]
the input mask plugin works fine on in the add record window using this In <body> of index.php:
            .....
        <div id="addform">

            <div class="row">
                <input type="text" id="chassi" name="chassi" placeholder="chassi" data-inputmask="'mask': '#################', 'placeholder': '.'" />
            ........
        </div>
		<script type="text/javascript">
			$(document).ready(function(){
				$(":input").inputmask();
			});
		</script>

What I can't find out is how to make it work in the grid

**Comment by jybeaujean** [comment]
You must create a dedicated editor. Check this: https://github.com/webismymind/editablegrid/blob/master/editablegrid_editors.js.

We do a similar thing in DateCellEditor.  You have to create InputMaskEditor and bind inputMask in displayEditor() 

Something like that : 
<pre>
InputMaskEditor.prototype.displayEditor = function(element, htmlInput) 
{
	// call base method
	TextCellEditor.prototype.displayEditor.call(this, element, htmlInput);
	$(htmlInput).inputmask("99-9999999");
};
</pre>
