### ISSUE TITLE
Displaying Images

### ISSUE THREAD

**Issue by rmingas** [jybeaujean/editablegrid-mysql-example#22]
I've stored image links on MySQL database. Is there a way they can be displayed in the grid?

**Comment by jybeaujean** [comment]
For sure. You have to define a renderer on the apporpriate column. Like this 
<pre>
	grid.setCellRenderer("thumb", new CellRenderer({ 
		render: function(cell, value) {           
			cell.innerHTML = "&lt;img src=\""+value+"\" alt=\""+value+"\" title=\"\" /&gt;";
		}
	}));

</pre>

**Comment by rmingas** [comment]
Thank You very much

**Comment by discreditable** [comment]
I'd love to see a minimal working demo/tutorial for this because while I can get other parts of the grid to work (loading json data encoded from mysql, adding/updating data, etc.) for the life of me I cannot figure out how to implement the code provided above.
