### ISSUE TITLE
Datepicker - monday first day of the week

### ISSUE THREAD

**Issue by schaff029** [jybeaujean/editablegrid-mysql-example#23]
Hey!
I'm using your editablegrid and have a question/problem:
I want to begin my datepicker with monday instead of sunday. How do I solve that issue? As far as I know do you initialize the datepicker in editablegrid-2.1.0-b25.js but that is not really readable.

Thanks!

**Comment by jybeaujean** [comment]
DateCellEditor is defined here : https://github.com/webismymind/editablegrid/blob/master/editablegrid_editors.js

To solve your problem define your own datecell editor ( based on DateCellEditor ) and use it on your column.
