### ISSUE TITLE
url in a cell

### ISSUE THREAD

**Issue by sabineCa** [jybeaujean/editablegrid-mysql-example#57]
Hi, 
I would like to add the same url for each cell of a column but my column is not a field of the table.
It's a manually added column with no link to the database.

How to add a link in its cells? the link will have to be stored in a php array..

**Comment by mtabdar** [comment]
hi
i think you can use another column (just duplicate a column like ID for example) and set it as url column. also change it so that in the cells you can see something like "LINK" and in cell render set the url!
i hope i am clear, i will try to put an example later

**Comment by sabineCa** [comment]
it's ok ! 
thanks !
