### ISSUE TITLE
Question(s)

### ISSUE THREAD

**Issue by debow77** [jybeaujean/editablegrid-mysql-example#8]
1) Is which css file is the column header position changed. I'm trying to get the column headers centered but nothing I've tried is working.

2) Is it possible to only have the Action column show up when a user is logged in? I wasn't sure how it would affect the xml etc. Same goes for editing. I'm wanting the data to be view-able to everything but only admin's can edit/delete etc. 

3) Is it possible to hide the column <action> if a user isn't logged in. I don't want all users to be able to delete rows, just ones logged in or logged in as an admin user etc.I'm not sure how to hide that since the column is rendered in js. I kind of faked it so that a non-logged in user can't delete but they still still the icon and column. I have this in the loaddata.php

if (!isset($_SESSION['user_id'])) {
    $grid->addColumn('action', '', '', NULL, false, ''); 
} else {	
   $grid->addColumn('action', 'Del Action', 'html', NULL, false, 'id');
}
 
4) Also I see from other posts that it sounds like you may still be working on this project. If that's the case are you planing on adding "rows per page" functionality?

Awesome work by the way.

**Comment by jybeaujean** [comment]
Hi

1) style.css, line 92 : table.testgrid th
2) For sur it's possible. You can test if your user is logged in loaddata.php. If not, return an empty array of data.
3)yes
4) rows per page can be defined in the constructor : demo.js, line 55 : pageSize: 10,
